if "%TARGET_ARCH%"=="x86" set TARGET_ARCH=win32

if "%MSVC_VERSION%"=="7.0" set MSVC_VERSION=2002
if "%MSVC_VERSION%"=="7.1" set MSVC_VERSION=2003
if "%MSVC_VERSION%"=="8.0" set MSVC_VERSION=2005
if "%MSVC_VERSION%"=="9.0" set MSVC_VERSION=2008
if "%MSVC_VERSION%"=="10.0" set MSVC_VERSION=2010
if "%MSVC_VERSION%"=="11.0" set MSVC_VERSION=2012
if "%MSVC_VERSION%"=="12.0" set MSVC_VERSION=2013
if "%MSVC_VERSION%"=="14.0" set MSVC_VERSION=2015
if "%MSVC_VERSION%"=="14.1" set MSVC_VERSION=2017
if "%MSVC_VERSION%"=="14.2" set MSVC_VERSION=2019
if "%MSVC_VERSION%"=="14.3" set MSVC_VERSION=2022

if not "%MSVC_PLATFORMTOOLSET%"=="" goto MSVC_PLATFORMTOOLSET_DONE
if "%MSVC_VERSION%"=="2010" set MSVC_PLATFORMTOOLSET=v100
if "%MSVC_VERSION%"=="2012" set MSVC_PLATFORMTOOLSET=v110
if "%MSVC_VERSION%"=="2013" set MSVC_PLATFORMTOOLSET=v120
if "%MSVC_VERSION%"=="2015" set MSVC_PLATFORMTOOLSET=v140
if "%MSVC_VERSION%"=="2017" set MSVC_PLATFORMTOOLSET=v141
if "%MSVC_VERSION%"=="2019" set MSVC_PLATFORMTOOLSET=v142
if "%MSVC_VERSION%"=="2022" set MSVC_PLATFORMTOOLSET=v143
:MSVC_PLATFORMTOOLSET_DONE

@rem gettext
set PATH=%TOOLS_DIR%\gettext-0.14.4-bin\bin;%PATH%

@rem other tools wget awk nasm patch
set PATH=%TOOLS_DIR%\bin;%PATH%

@rem 7zip
set PATH=%SEVENZIPPATH%;%PATH%

@rem perl
set PATH=%PERLHOME%\perl\bin;%PATH%

@rem python and scons
set PYTHONPATH=%PYTHONHOME%
set PATH=%PYTHONPATH%;%PYTHONPATH%\Scripts;%PATH%
set PYTHONSTARTUP=
if exist "%PYTHONPATH%\Lib\ppp.py" set PYTHONSTARTUP="%PYTHONPATH%\Lib\ppp.py"
set SCONSCMD=python "%TOOLS_DIR%\scons-local\scons.py"
